# mesh_rust_ci.yml (updated)

name: Mesh Rust CI

on:
  push:
    paths-ignore:
      - 'archive/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --verbose
      - name: Run All Tests (including Seed Node & Gossip Trust)
        run: cargo test --verbose
