name: Validate Files

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install pytest
        run: pip install pytest

      - name: Run validation
        run: pytest tests/test_task_bridge_runner.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: validate-results
          path: ./tests/

